language: python

python:
  - "3.6.6"


install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov
  - pip install pytest pytest-cov


script:
  - pytest
  - py.test test/ 
  - py.test --cov=app

after_success:
  - coveralls