language: python

python:
  - "2.7"


install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov


script:
  - pytest
  - py.test test/ 

after_script:
  - coveralls
   - codecov