language: python

python:
  - "2.7"


install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov

script:
  - coverage run tests.py
  - pytest

after_script:
  - codecov
  - coveralls

   